name: check

on:
  - push
  - pull_request

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - name: install
        run: |
          make install
        env:
          CI: true
      - name: Run test
        run: |
          make test
      - name: Run linter
        run: |
          make lint
      - name: Test & publish code coverage
        #   # Publish code coverage on Code Climate
        #   # https://github.com/paambaati/codeclimate-action
        uses: paambaati/codeclimate-action@v2.7.4
        #   # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
